### ISSUE TITLE
Minimap for file changes

### ISSUE THREAD

**Issue by dig412** [Ents24/Crew#6]
When reviewing changes for very long files, it can be hard to find the actual changes - you have to scroll down quickly and spot the green / red lines as they pass.

Could something like this:
https://github.com/samcroft/mini-map
or
https://github.com/princejwesley/minimap/issues
be implemented to give an overview of where the changes are in the file?

**Comment by bztsrc** [comment]
Just a suggestion: "hide/show unchanged lines" link next to "Hide whitespace"? This is easy as

```
$('tr > td[class="line "]').parent().toggle();
```
